spring:
  application:
    name: portal
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
