spring:
  application:
    name: portal
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
