spring:
  application:
    name: portal
server:
  port: 8080
eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
