spring:
  application:
    name: eureka
server:
  port: 80
eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka/eureka/